### ISSUE TITLE
Add angulartics as bower dependency

### ISSUE THREAD

**Issue by kylealwyn** [prestonvanloon/newrelic-angular#25]
If I can get around to it, I'll submit a pull. Otherwise, awesome lib!

**Comment by kylealwyn** [comment]
Realized you packaged it up in the build from npm. May be better to use dependency system though

**Comment by prestonvanloon** [comment]
Yeah there could be some redundancy if this library includes angulartics a second time. If you can submit a PR, I'll merge it. Thanks!

**Comment by prestonvanloon** [comment]
The only issue is that angulartics-newrelic-insights is not published anywhere. I've created an issue for that here: https://github.com/angulartics/angulartics-newrelic-insights/issues/1 and hopefully we can get something going here.
