### ISSUE TITLE
Why is there a call to reset this.logs?

### ISSUE THREAD

**Issue by globalchubby** [prestonvanloon/newrelic-angular#34]
Looking at the [source](https://github.com/angular/angular.js/blob/master/src/ng/log.js), there is no `logs` property.

In the Chrome console,

![image](https://cloud.githubusercontent.com/assets/2729079/15224772/114a6d52-1830-11e6-86b8-5a1cf527937d.png)

`$log` just delegates calls to `console`, so I'm wondering if [this line](https://github.com/prestonvanloon/newrelic-angular/blob/master/src/decorators/log.js#L42) is necessary.

**Comment by prestonvanloon** [comment]
It's more so for `angular-mocks`. Removing that line breaks tests. 

https://github.com/angular/bower-angular-mocks/blob/master/angular-mocks.js#L300

**Comment by globalchubby** [comment]
Thanks for the reply.

**Comment by globalchubby** [comment]
Wait, shouldn't this be done in the test setup?

**Comment by prestonvanloon** [comment]
`angular-mocks` is adding the `logs` property to $log actions, but this module replaces $log.error with a new object and `logs` is not carried over. We should consider something like this: 

``` javascript
Object.keys(originalFn).forEach(function(key) {
  if(originalFn.hasOwnProperty(key)) {
    fn[key] = originalFn[key];
  }
});

return fn;
```

This would handle `logs` and any other property that was added on `$log.error`
