### ISSUE TITLE
Adding to statusesToIgnore

### ISSUE THREAD

**Issue by boarnoah** [prestonvanloon/newrelic-angular#56]
Sorry not sure why I can't add the question label to this. 

Need to somehow ignore certain request failures (one of our requests is ignored silently server side, and the team would like to not have this get logged onto newrelics).

I would think the best way to achieve this would be to add the status to the statusesToIgnore to ignore array, i.e 

```
var statusesToIgnore = [-1];
```

for reference the rejection in question looks like this:

```
{
  "data": null,
  "status": -1,
  "config": {
    "method": "GET",
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "params": {
      "s": "search query goes here",
      "p": null,
      "c": null
    },
    "timeout": {
      "$$state": {
        "status": 0,
        "pending": [
          [
            {
              "promise": {
                "$$state": {
                  "status": 0
                }
              }
            },
            null,
            null,
            null
          ]
        ]
      }
    },
    "url": "\/autocomplete?versionId=xxxx",
    "headers": {
      "Accept": "application\/json, text\/plain, *\/*"
    }
  },
  "statusText": ""
}
```

which isn't much to work with. 

Sort of new to this module, just want to confirm if something like this would have any unexpected drawbacks? I'm wondering if I should consider adding a apiCallsToIgnore which would ignore the /autocomplete request specifically.

Thoughts are welcome, thanks.

**Comment by prestonvanloon** [comment]
Heyo!

Excellent question. You can set the statuses to ignore with the `httpInterceptorProvider` like this:

``` javascript
angular.module('myApp', ['newrelic-angular'])
   .config(function(httpInterceptorProvider) {
       httpInterceptorProvider.setStatusesToIgnore([-1]);
   });
```

I think this should be added to the readme. Let me know if it solves your problem and I'll add it to the readme.

**Comment by boarnoah** [comment]
Hey, sorry didn't see the notification for you reply. 

Looking further I was confident enough to say that status -1 only happens with such mia requests (404s, 500s are all logged properly), so I went ahead and set it up to ignore -1 with httpInterceptorProvider like you mention and it works fine, passed the tests.

Thanks you very much, and yes it would be great to see in the documentation =)
